name: Auto Sync main to main-3

on:
   push:
       branches:
          - main 
jobs:
   sync:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout main branch
       uses: actions/checkout@v3
       with:
          fetch-depth: 0
          ref: main

     - name: Set up Git
       run: |
         git config user.name "${{ github.actor }}"
         git config user.email "${{ github.actor }}@users.noreply.github.com"

     - name: Checkout main-3 branch
       run: |
         git checkout main-3 || git checkout -b main-3 origin/main

     - name: Merge main branch
       run: |
         git merge origin/main

     - name: Push changes to main-3
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main-3
